name: Sleekbyte
description: We are Sleekbyte
url: "https://sleekbyte.com"
github_url: "https://github.com/sleekbyte"

exclude: [README.md, LICENSE.md, CNAME, Gemfile, Gemfile.lock, vendor, script]

sass:
  style: compressed
